excluded:
    .build

opt_in_rules:
    - force_unwrapping
    - opening_brace

force_unwrapping:
    severity: error

trailing_whitespace:
    severity: error

identifier_name:
    allowed_symbols:
        - _
    excluded:
        - id
        - ok
        - n
        - v1

type_name:
    allowed_symbols:
        - _TupleContent
        - _OptionalContent
        - _ConditionalContent
        - _EncodablePayload
        - _DataPayload
        - _DictionaryPayload
        - _StringPayload
    excluded:
        - ID

large_tuple:
    warning: 9
    error: 16

nesting:
    type_level: 
        warning: 4
        error: 6

