name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    permissions:
      issues: write
      pull-requests: write
    uses: swift-bloc/.github/.github/workflows/auto-assign.yml@main
    secrets: inherit