name: Code Coverage

on:
  push:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/code-coverage.yml'

jobs:
  code-coverage:
    uses: swift-bloc/.github/.github/workflows/code-coverage.yml@main
    with:
      package-tests: blocPackageTests
      target: Bloc
    secrets: inherit
