name: Generate Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-release:
    permissions:
      contents: write
      pull-requests: write
    uses: swift-bloc/.github/.github/workflows/generate-release.yml@main
    secrets: inherit
